default_platform(:ios)

platform :ios do
  desc "Upload an exported LifeLinked IPA to TestFlight"
  lane :upload_testflight do |options|
    ipa_path = options[:ipa] || ENV.fetch("LIFELINKED_IOS_IPA_PATH")

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("LIFELINKED_APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("LIFELINKED_APP_STORE_CONNECT_ISSUER_ID"),
      key_filepath: ENV.fetch("LIFELINKED_APP_STORE_CONNECT_API_KEY_PATH"),
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa_path,
      app_identifier: "com.hypeapps.LifeLinked",
      skip_waiting_for_build_processing: true
    )
  end
end
